import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {PrismaClient} from '@prisma/client';
import React, {Fragment, useState} from 'react'
import Link from 'next/link';

const prisma = new PrismaClient();

export default function Home({ data }) {

const [formData,setFormData] = useState ({})
const [movies,setMovies] = useState(data)

async function saveMovie(e) {
  e.preventDefault();

  setMovies([...movies,formData])
  
const response = await fetch('/api/movies',{
  method: 'POST',
  body: JSON.stringify(formData)
})


}


  return (
    <div className={styles.container}>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
 <ul >
   {movies.map(item  => {
     return (
       
      <Fragment key={Math.floor(Math.random()*10000)}>
     <li ><br/>
       <span ><strong>{item.title}</strong></span><br/>
       <span>{item.year}</span><br/>
       <span>{item.description}</span><br/>
       <Link href={`/movies/${item.slug}`}>
         <a>More About This Movie</a>
       </Link>
      
       </li>
      </Fragment>
     
     )
     })}
 </ul>

<form onSubmit={saveMovie}>
<input type="text" placeholder="Title" name="title" onChange={e => setFormData({...formData,title: e.target.value})}/>
<input type="number" placeholder="Year" name="year" onChange={e => setFormData({...formData,year: +e.target.value})}/>
<textarea name="description" id="" cols="30" rows="10" placeholder="description"
onChange={e => setFormData({...formData, description: e.target.value})}/>
<input type="text" placeholder="Slug" name="slug" onChange={e => setFormData({...formData,slug: e.target.value})}/>
<button type="submit">Add Movies</button>
</form>


      </main>

      
    </div>
  )
}


export async function getServerSideProps() {


const movies = await prisma.movie.findMany();



return {
  props: {
    data:movies
  }
}
}